spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
ospp:
  timeLimit: 3600 # 1h
  testMode: true

server:
  address: 0.0.0.0