spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

ospp:
  solver: ch.fhnw.ip6.ortoolssolver.Solver
  timeLimit: 360 # 1h
  testMode: NORMAL
server:
  address: 0.0.0.0
logging:
  file:
    name: ospp-application.log
    path: ./logs/