spring:
  datasource:
    url: jdbc:mysql://db-ospp.cpfp7kii5qy2.eu-central-1.rds.amazonaws.com:3306/osppdb?useUnicode=yes&characterEncoding=UTF-8
    username: osppuser
    password: 2QXHYrCjwNthHi4h8FY9Go2s7r3i8s
    #url: jdbc:h2:mem:testdb
    #driverClassName: org.h2.Driver
    #username: sa
    #password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

ospp:
  solver: ch.fhnw.ip6.cpsolver.Solver
  timelimit: 10
  testmode: true