spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

ospp:
  solver: ch.fhnw.ip6.cpsolver.Solver
  timelimit: 180
  testmode: false

server:
  address: 0.0.0.0