spring:
  banner:
    location: banner-test.txt
  profiles: test
  datasource:
    url: jdbc:mysql://ospp-db:3306/osppdb?autoReconnect=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    username: ospp
    password: Change_me_2020
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create


ospp:
  solver: ch.fhnw.ip6.ortoolssolver.Solver
  timeLimit: 300 # in seconds
  testmode: false
