spring:
  datasource:
    url: jdbc:mysql://ospp-db.c1xzf7r3bjyl.eu-central-1.rds.amazonaws.com:3306/osppdb?useUnicode=yes&characterEncoding=UTF-8
    username: osppuser
    password: 67vF7ainrLrXYNc
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


ospp:
  solver: ch.fhnw.ip6.cpsolver.Solver
  timelimit: 300
  testmode: false
