spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/osppdb
    username: ospp
    password: Change_me_2020
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
ospp:
  timeLimit: 3600 # 1h
  testMode: true

server:
  address: 0.0.0.0