server:
  port: 5000

spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
    url: jdbc:mysql://aa27badiyw1u2j.cpfp7kii5qy2.eu-central-1.rds.amazonaws.com  :3306/ebdb
    username: osppawsdb
    password: 2QXHYrCjwNthHi4h8FY9Go2s7r3i8s
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect