name: Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build  -t ospp-backend .
        working-directory: BackEnd
      - name: Docker Tag
        run: |
          docker tag ospp-backend bananenhoschi/ospp-backend:${{ github.sha }}
          docker tag ospp-backend bananenhoschi/ospp-backend:latest
        working-directory: BackEnd
      - name: Docker Push
        run: |
          docker push bananenhoschi/ospp-backend:${{ github.sha }}
          docker push bananenhoschi/ospp-backend:latest
        working-directory: BackEnd
