name: Docker Image

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  cd:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build -f Dockerfile.test -t ospp-application .
      - name: Docker Tag
        run: |
          docker tag ospp-application bananenhoschi/ospp-application:${{ github.sha }}
          docker tag ospp-application bananenhoschi/ospp-application:latest
      - name: Docker Push
        run: |
          docker push bananenhoschi/ospp-application:${{ github.sha }}
          docker push bananenhoschi/ospp-application:latest

