name: Docker Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login -u ${{secerts.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: docker build . --file Dockerfile
        working-directory: BackEnd
      - name: Docker Tag
        run: |
          docker tag ${{ secrets.DOCKER_USER }}/ospp-backend:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USER }}/ospp-backend:latest
        working-directory: BackEnd
      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/ospp-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/ospp-backend:latest
        working-directory: BackEnd
